plugins:
  # - jest
  - fp

env:
  jest: true
  node: true
  es2020: true

extends:
  - airbnb-base
  # - "plugin:jest/recommended"
  # - "plugin:fp/recommended"


rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-unused-vars: 'warn'
  # fp/no-nil: 0
  # fp/no-unused-expression: 0
  # fp/no-throw: 0
  # fp/no-mutating-methods:
  #   - error
  #   - allowedObjects:
      # - "_"
